# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## 1. Загрузка данных

In [15]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from itertools import product

In [16]:
data = pd.read_csv('/datasets/insurance.csv')
data

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0       1     41.0   49600.0            1                  0
1       0     46.0   38000.0            1                  1
2       0     29.0   21000.0            0                  0
3       0     21.0   41700.0            2                  0
4       1     28.0   26100.0            0                  0
...   ...      ...       ...          ...                ...
4995    0     28.0   35700.0            2                  0
4996    0     34.0   52400.0            1                  0
4997    0     20.0   33900.0            2                  0
4998    1     22.0   32700.0            3                  0
4999    1     28.0   40600.0            1                  0

[5000 rows x 5 columns]

In [17]:
data.isna().sum()

Пол                  0
Возраст              0
Зарплата             0
Члены семьи          0
Страховые выплаты    0
dtype: int64

In [18]:
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']

## 2. Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Не изменится.
$$
w’ = P^{-1} w
$$

**Обоснование:**  вектор весов линейной регрессии одинковый в обоих случаях 


## 3. Алгоритм преобразования

**Алгоритм**

Линейная регрессия, чтобы найти прямую с нужными коэффициентами, использует формулу 
$$
w = (X^T X)^{-1} X^T y
$$

где Х - матрица с признаками, у вектор целевого признака, 𝑤  — вектор кофицентов линейной регрессии

$$
w^{0} = ((XY)^{T}XY^{-1})(XY)^{T}y
$$


$$
a = Xw
$$

Где а - вектов предсказаний обученный по X

$$
a' = w^{0}XY
$$

где Y - это рандомная обратимая матрица такая же по размеру как X, $a^{0}$- вектов предсказаний обученный по XY

$$
a = a^{0}
$$

**Обоснование**
Используя свойство умножение матрицы на свою обратную - есть единичная матрица
$$
a = (X^T X)^{-1} X^T yT = y(X^T X)^{-1} X^TX = yE = y
$$

E - единичная матрица

$$
MSE = \frac1n\sum _{i=1}^{n}(a_{i}-{y_{i}})^{2} = 0
$$

Проверим что будет если мы сделем тоже самое с $a^{0}$

$$
a^{0} = ((XY)^{T}XY^{-1}(XY)^{T}yXY = y((XY)^{T}XY^{-1}((XY)^{T} XY) = yE = y
$$

$$
MSE = \frac1n\sum _{i=1}^{n}(a_{i}^{0}-{y_{i}})^{2} = 0
$$

$a = y$, $a^{0} = y$
Теперь у свереностью можно сказать, что наши предсказания равны целевому признаку 

In [19]:
x = np.random.rand(5,5)
a = 0
for comb in range(10):
    try:
        print(x)
        inverse = np.linalg.inv(x)
    except np.linalg.LinAlgError:
        pass
    else:
        a = x
        break

[[0.41604388 0.6638737  0.61427255 0.47694396 0.0963841 ]
 [0.55608418 0.17428151 0.90001083 0.06584112 0.9434252 ]
 [0.08204786 0.89821665 0.18658335 0.19412414 0.38208425]
 [0.21075062 0.49552232 0.7190679  0.50299307 0.65850094]
 [0.82464312 0.09286969 0.490641   0.0452318  0.39437854]]


In [20]:
np.linalg.inv(x)

array([[-0.46755733, -1.13803064,  0.16005598,  0.34052669,  2.11299494],
       [ 0.70873513,  0.45010717,  1.18355926, -1.14398269, -0.48648418],
       [ 2.49053088,  2.59962756, -0.92367584, -2.13198592, -2.37275842],
       [-1.25642621, -2.85398721, -0.72243094,  3.6798939 ,  1.68984562],
       [-2.14357054, -0.6332116 ,  0.61860424,  1.78767286,  0.99004044]])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 4. Проверка алгоритма

In [22]:
class LinearRegression:
    def fit(self, train_features, train_target):
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1)
        y = train_target
        w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
        self.w = w[1:]
        self.w0 = w[0]

    def predict(self, test_features):
        return test_features.dot(self.w) + self.w0
    
model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
print('R2-', r2_score(target, predictions))

R2- 0.4249455028666801


In [27]:
class LinearRegression1:
    def fit(self, train_features, train_target):
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1)
        Y = a
        y = train_target
        w  = np.dot(np.linalg.inv(np.dot((np.dot(X, Y)).T, np.dot(X, Y))), np.dot((np.dot(X, Y)).T, y))
        self.w = w[1:]
        self.w0 = w[0]

    def predict(self, test_features):
        print(test_features)
        return test_features.dot(self.w) + self.w0
    
features_new = features.dot(a[1:])    
model1 = LinearRegression()
model1.fit(features_new, target)
predictions1 = model1.predict(features_new)
print('R2_шифрования-', r2_score(target, predictions1))

R2_шифрования- 0.4114531178546995


In [ ]:
features_new = features.dot(a[1:,1:])

In [33]:
model1 = LinearRegression()
model1.fit(features_new, target)
predictions1 = model1.predict(features_new)
print('R2_шифрования-', r2_score(target, predictions1))

R2_шифрования- 0.4249455028636122


********************************

коэффициента детерминации близок к нулю